[tool.poetry]
name = "nep-lms"
version = "0.1.0"
description = ""
authors = ["Sanjaya Subedi <jangedoo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
torch = "^2.4.0"
datasets = "^2.21.0"
transformers = "^4.44.2"
accelerate = "^0.33.0"
sentence-transformers = "^3.0.1"
lets-plot = "^4.4.1"
easyknn = "^0.5.0"


[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
rope = "^1.13.0"
flake8 = "^7.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
